/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IRegistryContract,
  IRegistryContractInterface,
} from "../IRegistryContract";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes",
        name: "pubkey",
        type: "bytes",
      },
      {
        indexed: true,
        internalType: "bytes",
        name: "idCommitment",
        type: "bytes",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
    ],
    name: "RegistrationEvent",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "pubkey",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "idCommitment",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
    ],
    name: "register",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IRegistryContract__factory {
  static readonly abi = _abi;
  static createInterface(): IRegistryContractInterface {
    return new utils.Interface(_abi) as IRegistryContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRegistryContract {
    return new Contract(address, _abi, signerOrProvider) as IRegistryContract;
  }
}
