/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRegistryContract } from "./IRegistryContract";
export type { RegistryContract } from "./RegistryContract";

export { IRegistryContract__factory } from "./factories/IRegistryContract__factory";
export { RegistryContract__factory } from "./factories/RegistryContract__factory";
